### PR TITLE
upgrading to angular 16

### PR DESCRIPTION
**Pull request by sushilnyk**

### CODE REVIEW

**Comment by ralftar** [comment]
Hi! Thanks for the PR! Is it tested and ready to merge?

**Comment by sushilnyk** [comment]
Hi 
This has been tested . I checked the demo UI and didnot find any issues . There were some CLI warnings during build but I think they can be ignored . 
Thanks

**Comment by drumondbeto** [comment]
Hi

Can anyone complete the PR, please?
I'm waiting for this update. This lib is no linger compatible with my project and i want this update so bad.

Thanks.

**Comment by hsoohail** [comment]
Hi,

Can we have this merged please. Thank you.

**Comment by ralftar** [comment]
I think all the dependencies needs bumps to, the CICD broke: https://github.com/ralftar/ng-mat-carousel/actions/runs/7171207428 
Feel free to PR this.

**Comment by attilacsanyi** [comment]
> I think all the dependencies needs bumps to, the CICD broke: https://github.com/ralftar/ng-mat-carousel/actions/runs/7171207428 Feel free to PR this.

How about this simple PR: https://github.com/ralftar/ng-mat-carousel/pull/258 is this ok and help? Thanks @ralftar

**Comment by attilacsanyi** [comment]
PR still failing I just [updated the lock file](https://github.com/ralftar/ng-mat-carousel/pull/258), but it seem it was not enough, any idea? The `postinstall` [is failing](https://github.com/ralftar/ng-mat-carousel/actions/runs/7210596226/job/19719301146?pr=258) here is the issue from CI:
```shell
...
> esbuild@0.19.9 postinstall /home/runner/work/ng-mat-carousel/ng-mat-carousel/node_modules/ng-packagr/node_modules/esbuild
> node install.js


> nx@16.5.1 postinstall /home/runner/work/ng-mat-carousel/ng-mat-carousel/node_modules/nx
> node ./bin/post-install

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
...
```

**Pull request merged**
